apiVersion: v1
kind: Pod
metadata:
  name: NAME
spec:
  containers:
  - name: NAME
    image: IMAGE
    imagePullPolicy: IfNotPresent
    env:
      - name: REGISTRY_IP
        value: IP
      - name: REGISTRY_PORT
        value: PORT
  nodeSelector:
    node: NODE
